movie:
  randomLimit: 3

genre:
  refreshCron: "0 0 */4 * * ?"

currency:
  url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json"
  refreshCron: "0 0 8 * * ?"

session:
  expirationHours: 2
  cleanMillis: 300000 # 5*60*1000

db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7281012
  username: sql7281012
  password: VrWWk6FjKA
  maxTotal: 20
  minIdle: 2
  maxIdle: 10
  maxWaitMillis: 10000
